spring:
  application:
    name: nowcode-mcp-server
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        instructions: 牛客网面经搜索工具
#  main:
#    banner-mode: off
#    web-application-type: none

logging:
  file:
    name: data/log/${spring.application.name}.log
#  pattern:
#    console:

server:
  port: 10088